
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: fb-development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PW'] %>
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fb-test
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PW'] %>
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  <<: *default
  pool: 25
#  database: fakebook_production
#  username: fakebook
#  password: <%= ENV['FAKEBOOK_DATABASE_PASSWORD'] %>
